### ISSUE TITLE
To use rewire, but give me error!

### ISSUE THREAD

**Issue by sunfeng90** [jhnns/rewire#111]
> //index.js
> module.exports = function(CheckCode) {
>   var getRandomInt = (min, max) => {
>     return Math.floor(Math.random() * (max - min + 1) + min);
>   }
> };
> 
> //index.test.js
> const checkCodeModel = rewire('../index.js');
> let getRandomInt = checkCodeModel.__get__('getRandomInt');

Error: output getRandomInt is not defined, why?

**Comment by sunfeng90** [comment]
I write '__get__' but show the get

**Comment by jhofker** [comment]
Are your files in the same folder? Your relative path in the test implies they aren't, but that could be something to check.

To get it to show up as `__get__(...)` on here, use the back tick character (`) to do it inline, or do three of them in a row on a new line (```), then your code, then three more on another line.
```
to do a block of code
```

**Comment by sunfeng90** [comment]
Thx!The files in the same folder.The  rewire support export the closure function?

**Comment by jhnns** [comment]
Nope. Accessing variables inside a function closure is not possible.
