### ISSUE TITLE
TypeError: Class constructor Alg1 cannot be invoked without 'new'

### ISSUE THREAD

**Issue by rnemec** [jhnns/rewire#119]
I have two classes: `Alg1 extends Alg2`.
When I `rewire` Alg2 and call its constructor `new Alg2()`,I get the error in the title.
Only fails on `3.0.0`. Downgrading to 2.5.2 for now - all works fine there.

**Comment by JvJefke** [comment]
Could you give the exact error?

**Comment by rnemec** [comment]
`TypeError: Class constructor Alg1 cannot be invoked without 'new'`
😄

**Comment by JvJefke** [comment]
I cannot reproduce this error. Would you be willing to give some example code where you experience this error?

**Comment by rnemec** [comment]
Node: 8.9.1
I'll try to find some time to create a reproducible example.

**Comment by rnemec** [comment]
Here is the most trivial example. Three files in the same folder.
`alg1.js`:
```js
class Alg1 {}
module.exports = Alg1;
```

`alg2.js`:
```js
const Alg1 = require('./alg1');
class Alg2 extends Alg1 {}
module.exports = Alg2;
```
`algtest.js`:
```js
const rewire = require('rewire');
const Alg = rewire('./alg2');
let a = new Alg();
```

Run `node algtest`, resulting in:
```
Alg2 = function (_Alg) {_inherits(Alg2, _Alg);function Alg2() {_classCallCheck(this, Alg2);return _possibleConstructorReturn(this, (Alg2.__proto__ || Object.getPrototypeOf(Alg2)).apply(this, arguments));}return Alg2;}(Alg1);
           ^

TypeError: Class constructor Alg1 cannot be invoked without 'new'
  at new Alg2 (/Users/rnemec/Projects/T/app/util/alg2.js:2:180)
  at Object.<anonymous> (/Users/rnemec/Projects/T/app/util/algtest.js:3:9)
  at Module._compile (module.js:635:30)
  at Object.Module._extensions..js (module.js:646:10)
  at Module.load (module.js:554:32)
  at tryModuleLoad (module.js:497:12)
  at Function.Module._load (module.js:489:3)
  at Function.Module.runMain (module.js:676:10)
  at startup (bootstrap_node.js:187:16)
  at bootstrap_node.js:608:3
```

**Comment by rnemec** [comment]
@JvJefke  - did the example help to reproduce? It's 3 files, total 8 lines of code, and it's 100% reproducible for me. Please, have a look

**Comment by JvJefke** [comment]
Thanks for the example!
I didn't yet have the time to look into this. I'll try to do it this evening.

**Comment by JvJefke** [comment]
I still can't reproduce this error. I added a test with your example, but it doesn't fail in node 8.9.1 on my computer.

see: https://github.com/JvJefke/rewire/commit/35d43982c8f11717761562fcc29b087b2dbd89f9

**Comment by rnemec** [comment]
Hmm, weird.

I wonder - do you babelize your tests? What happens if you just run the test (or just a code that rewire-s and instantiates, like my 3rd file) from command line using plain node?

**Comment by JvJefke** [comment]
I also ran it from command line using plain node and is still worked.

Rewire uses babel internally to convert constants (const) to variables (var), but the tests itself aren't babelized.

Could you perhaps pull the `bugfix/class-constructor` branche from my fork (https://github.com/JvJefke/rewire/tree/bugfix/class-constructor) and run `npm test`to see if it issue is environment related or not?

**Comment by rnemec** [comment]
Pulled the branch and `npm test` succeeds with 63 passing tests. Will play with it more to see what may be going on... One difference I see is that I'm using `rewire` as npm module, not running *inside*, like your tests.

**Comment by rnemec** [comment]
Oh, found what is causing it: I have a `.babelrc` in the project root that is used for some other code. When I temporarily remove the `babelrc`, rewire works OK. It seems that your use of `babel` picks up the babel setting in my project (and those settings are not rewire-friendly, apparently).

Please, let me know if there is anything I can do to help resolving this...
Oh, my `.babelrc` is:
```js
{
    "presets": ["es2015"],
    "plugins": ["transform-class-properties"]
}
```

**Comment by JvJefke** [comment]
I opened a PR to fix this: https://github.com/jhnns/rewire/pull/123.
Thanks a lot for reporting this and helping us look for a solution!

**Comment by rnemec** [comment]
My pleasure! Thanks guys for keeping this tool being one of top unit-testing utilities.
