### ISSUE TITLE
Very slow perfomance

### ISSUE THREAD

**Issue by jehy** [jhnns/rewire#138]
using **rewire@2** our 4000 unit tests take ~12 seconds (those run in one thread with mocha) .

using **rewire@3** produces SyntaxError which shows stack with valid rest params:

```
/web/xxx/node_modules/babylon/lib/index.js:4454
  var err = new SyntaxError(message);
            ^
SyntaxError: /web/xxx/yyy.js: Unexpected token (159:4)
  157 |                         .filter(trip => hasTrip(params.trips, trip))
  158 |                         .map(trip => ({
> 159 |                                 ...trip,
      |                                 ^
```

**rewire@4** works but same tests take 40 seconds(!!!) to accomplish : (

What can be wrong? We using Node 8.9.1.

**Comment by jameswilddev** [comment]
Something which I've found really helps with performance, for stateless modules, is to rewire only once, then create a function which wraps .__set__.  This function tracks all changes it made, and reverts them all at the end of the tests (in this case, Jasmine's "afterEach").

I'm not sure but it looks like you have an ES6 module being imported by a non-ES6 runtime.  Given Babylon (Babel's parser?) is in the stack, is your .babelrc definitely being loaded?

**Comment by jhnns** [comment]
- rewire 3 uses Babel to transform `const` to `let`. That's why it doesn't work with special syntax like the object spread operator
- rewire 4 uses a Regex to circumvent these issues. Can you create [a flame graph of your tests](https://nodejs.org/en/blog/uncategorized/profiling-node-js/) to pinpoint me to the direction where rewire spends the most time? @jehy

**Comment by jehy** [comment]
@jameswilddev we are running tests on Node.JS backend, there are no ES6 modules, only CommonJS.

**Comment by jehy** [comment]
@jhnns i tried to, but I can't find a working version of dtrace for ubuntu 18 :(
