### ISSUE TITLE
Type Error with `const`

### ISSUE THREAD

**Issue by Sufiane** [jhnns/rewire#144]
I face myself against a Type Error when trying to rewire a private `const`
I already have the last version `4.0.1`

I used the workaround using let but I would prefer to use const as I don't want to change my code only for test purposes

Demo:
index.js:

const myPromisifiedFunction = promisify(someFunct.ToPromisify)
index.test.js:

const myModule = rewire('../myModule')
const myStub = sinon.stub()
const revert = myModule.__set__('myPromisifiedFunction', myStub)
And what I get when running tests is:
TypeError: Assignment to constant variable. at eval (eval at __set__ (index.js:159:5), <anonymous>:1:19) at Object.__set__ (index.js:159:5) at Object.<anonymous> (test/index.test.js:14:48)

Thanks in advance for any help you could provide ! 

Edit: I'm aware of the #79 issue, I already commented on it but since it's closed I thought it would be better to open a new one

**Comment by Shakakai** [comment]
I'd like to provide some additional evidence. The issue appears to happen when using the Jest testing library but not with Mocha. I created a git repo to show the issue: https://github.com/Shakakai/jest-rewire-const-error

I'm posting this issue on the Jest github as well. I'll provide the link shortly.

**Comment by sinkersan** [comment]
Any updates here?

**Comment by missmatsuko** [comment]
I'm having the same problem, also using Jest!

**Comment by tyukesz** [comment]
+

**Comment by andreisaikouski** [comment]
I see this same issue in Mocha. Any suggestions / fixes?

**Comment by jhnns** [comment]
I've added a test case in the most recent version and I think this is not an issue anymore: https://github.com/jhnns/rewire/blob/f5c655a58300f0899a0f5de130bff6e9dcf3de81/testLib/sharedTestCases.js#L426-L432

**Comment by justinrush** [comment]
I'm still seeing this in rewire v6 / jest v27.4.5.

### db.js
```javascript
function connectDB() {
    console.log('in connectdb');
}
module.exports.connectDB = connectDB;
```

### constMod.js
```javascript
const { connectDB } = require('./db');

function doIt() {
    console.log('no');
    connectDB();
}

```

### constMod.test.js
```javascript
const rewire = require('rewire');
const db = require('./db');
const constMod = rewire('./constMod');

db.connectDB = jest.fn();

describe('constMod', () => {
    it('mocks connectDb', () => {
        constMod.__set__({
            connectDB: db.connectDB,
        });

        const doIt = constMod.__get__('doIt');
        doIt();
        expect(db.connectDB).toHaveBeenCalled();
    });
});

```


Output:
```
-> % npm run jest       

> js-test@1.0.0 jest /js-test
> jest

 FAIL  ./constMod.test.js
  constMod
    ✕ mocks connectDb

  ● constMod › mocks connectDb

    TypeError: Assignment to constant variable.

      at eval (eval at __set__ (constMod.js:72:5), <anonymous>:1:11)
      at Object.__set__ (constMod.js:72:5)
      at Object.<anonymous> (constMod.test.js:9:18)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        0.247 s, estimated 1 s
Ran all test suites.
```

**Comment by tyukesz** [comment]
> I'm still seeing this in rewire v6 / jest v27.4.5.
> ### db.js
> 
> ```js
> function connectDB() {
>     console.log('in connectdb');
> }
> module.exports.connectDB = connectDB;
> ```
> 
> ### constMod.js
> 
> ```js
> const { connectDB } = require('./db');
> 
> function doIt() {
>     console.log('no');
>     connectDB();
> }
> ```
> 
> ### constMod.test.js
> 
> ```js
> const rewire = require('rewire');
> const db = require('./db');
> const constMod = rewire('./constMod');
> 
> db.connectDB = jest.fn();
> 
> describe('constMod', () => {
>     it('mocks connectDb', () => {
>         constMod.__set__({
>             connectDB: db.connectDB,
>         });
> 
>         const doIt = constMod.__get__('doIt');
>         doIt();
>         expect(db.connectDB).toHaveBeenCalled();
>     });
> });
> ```
> 
> Output:
> 
> ```
> -> % npm run jest       
> 
> > js-test@1.0.0 jest /js-test
> > jest
> 
>  FAIL  ./constMod.test.js
>   constMod
>     ✕ mocks connectDb
> 
>   ● constMod › mocks connectDb
> 
>     TypeError: Assignment to constant variable.
> 
>       at eval (eval at __set__ (constMod.js:72:5), <anonymous>:1:11)
>       at Object.__set__ (constMod.js:72:5)
>       at Object.<anonymous> (constMod.test.js:9:18)
> 
> Test Suites: 1 failed, 1 total
> Tests:       1 failed, 1 total
> Snapshots:   0 total
> Time:        0.247 s, estimated 1 s
> Ran all test suites.
> ```

This could be because you are using object destructuring: `const { connectDB } = require('./db');`

**Comment by justinrush** [comment]
changing the main function to  use `const db = require('./db');` and then updating the test to be:
```
const db = require('./db');
const rewire = require('rewire');
const constMod = rewire('./constMod');

db.connectDB = jest.fn();

describe('constMod', () => {
    it('mocks connectDb', () => {
        const conndb = jest.fn();
        constMod.__set__('db', {
            connectDB: conndb,
        });
        const doIt = constMod.__get__('doIt');
        doIt();
        expect(conndb).toHaveBeenCalled();
    });
});

```

results in the same error

**Comment by vuphu** [comment]
Based on #149,  I used rewire for rewire module

```typescript
const rewireRef = rewire('rewire');
const moduleEnvRef = rewire('rewire/lib/moduleEnv.js');

const jsExtension = moduleEnvRef.__get__('jsExtension');
moduleEnvRef.__set__('jsExtension', () => {
    return function (module: any, filename: any) {
        jsExtension(module, filename);
    };
});
rewireRef.__set__('moduleEnv', moduleEnvRef);

const yourPackage = rewireRef('your-package')
```

I hope it works for your project.
