### ISSUE TITLE
Fix const regex is not in 4.0.1

### ISSUE THREAD

**Issue by brodybits** [jhnns/rewire#153]
It looks like 4.0.1 release was made with the fix from #139 in CHANGELOG.md but with the fix not included. Here is a screenshot from gitx:

![screen shot 2018-11-21 at 11 06 25 am](https://user-images.githubusercontent.com/1559888/48853623-e4caf000-ed7d-11e8-959b-3d8ef798b976.png)

**Comment by jhnns** [comment]
Not sure what the issue was but I think it's released now :)
