### ISSUE TITLE
Is there an actively maintained fork of this project?

### ISSUE THREAD

**Issue by cjancsar** [jhnns/rewire#173]
Is there an actively maintained fork of this project?

**Comment by rensbaardman** [comment]
I've got a fork that fixes the dependency issues: https://github.com/rensbaardman/rewire. Should be a drop-in replacement. Besides that, I don't think there is a lot of maintaining to do.

**Comment by paulineleon** [comment]
Is there an alternative ?

**Comment by TranquilMarmot** [comment]
If you switch to Jest, it has pretty robust module mocking capabilities built in. https://jestjs.io/docs/en/manual-mocks

**Comment by jhnns** [comment]
I've released a new version with some bug fixes and dependency updates. Besides that, I won't add new features or do bigger changes to the code base.
