### ISSUE TITLE
Possible to set variable during rewiring?

### ISSUE THREAD

**Issue by paulhutchings** [jhnns/rewire#180]
Is it possible to set the value of a variable at the same time as rewiring? I have this code:
```
if (typeof(mymodule) === 'undefined'){
    var mymodule = require('mymodule');
}
```
and would like to be able to override the `mymodule` variable when calling `rewire` so that the variable is defined with a mock, and doesn't try to load it from `node_modules`.

If this isn't possible with rewire, if anyone has any resources on how I could achieve this I would be most appreciative.

Thanks!

**Comment by georgezlei** [comment]
second this issue. `rewire` function can have an optional parameter to pass in variables. For example,
```
const target = rewire('./target', { toOverride: 'value' })
```

**Comment by jhnns** [comment]
I'm sorry, this is out of scope of the current design. The module needs to be evaluated in order to change the internals. Fixing or changing this would require a major rewrite.
