### ISSUE TITLE
Vulnerable dependancy eslint 7.32.0

### ISSUE THREAD

**Issue by awhtly** [jhnns/rewire#197]
Hi, 

There are some vulnerabilities within some dependencies that can be addressed by updating the dependency eslint.

https://github.com/jhnns/rewire/blob/f5c655a58300f0899a0f5de130bff6e9dcf3de81/package.json#L44

This updates a dependency call strip-ansi that used a vulnerable version of ansi-regex 

https://github.com/eslint/eslint/blob/6f940c3ce715327f282c197d0f71b91848e5d83d/package.json#L81

https://github.com/advisories/GHSA-93q8-gq69-wqmw

**Comment by wheatley** [comment]
#198
