### ISSUE TITLE
Rewire is great, but it doesn't work for SonarQube

### ISSUE THREAD

**Issue by ANTGOMEZ** [jhnns/rewire#209]
First, I love Rewire, makes things real easy. 

However, we started using SonarQube for quality gates, and all tests that use Rewire are not recognized as covered by SonarQube. 

When I rewrote the tests without using Rewire, the tests were recognized again by SonarQube. 

Could there be a Rewire config setting or something that would alleviate this?

**Comment by jhnns** [comment]
Thank you for your kind words. I have no idea what SonarQube is and why it doesn't work.
