### ISSUE TITLE
Mongoose model overwrite error

### ISSUE THREAD

**Issue by csugden** [jhnns/rewire#27]
I've used rewire with a Mongoose model in a jasmine spec, and also used require to load the same model in a different spec. I get this error:

```
{ message: 'Cannot overwrite `Organisation` model once compiled.', name: 'OverwriteModelError' }
```

It looks like it's asking Mongoose to define the same model twice, whereas if we used require both times this does not happen.

Is there a workaround?

Thanks.

**Comment by neverfox** [comment]
@Trindaz Could you provide an example of how you actually use that function? Thanks!

**Comment by neverfox** [comment]
I believe this would work in most scenarios where you need to re-register a mongoose model:

```js
delete mongoose.connection.models['Cat'];
// proceed with rewire, proxyquire, etc.
```
