### ISSUE TITLE
Code coverage tool does not recognize rewired modules

### ISSUE THREAD

**Issue by mghaderyan** [jhnns/rewire#38]
Hi, 
I am using Istanbul for coverage reports and I realized it does not consider the rewired modules "covered". For example if myModule.coffee is the source and myModule.spec.coffee is the test containing the following:

```
myModule = rewire 'src/myModule'
```

Is there a way to fix this?
Regards

**Comment by jhnns** [comment]
It looks like istanbul does not support code instrumentation for CoffeeScript (https://github.com/gotwarlost/istanbul/pull/167). You'll need to compile your CoffeeScript to JavaScript before instrumenting it...

**Comment by mghaderyan** [comment]
I see. Thanks for that

**Comment by willmorgan** [comment]
@jhnns I think the Babel upgrade to allow const has made this an issue again, as I'm seeing this in the newest version.

**Comment by JvJefke** [comment]
@jhnns It might be worth to look into something like this: https://github.com/istanbuljs/babel-plugin-istanbul. I'll check it out when I have time but it will not be for the this week.

**Comment by jhnns** [comment]
@willmorgan @JvJefke thanks for pointing out. Does istanbul expose an environmental flag?

**Comment by willmorgan** [comment]
@jhnns I've had a quick look, and it doesn't look like there's anything in the docs to suggest it does 😞

**Comment by willmorgan** [comment]
@jhnns Just read the changelog - great work. I see that this is quite a nuanced issue. I'll upgrade rewire on our end and see if it plays nice with istanbul.

**Comment by willmorgan** [comment]
@jhnns Update: this looks way better. I think we can close it. Thanks again! 🎉

**Comment by rodrigoreis22** [comment]
I'm using jest 23.4.1 for a node.js (v 8.10) project and after using rewire my code coverage report doesn't work anymore. Any ideas? I'm not sure jest uses istanbul..

**Comment by shengbolou** [comment]
using create-react-app with rewire, the code coverage report is not able to recognize rewired modules.

Appreciate any help!

**Comment by chandlerlucius** [comment]
Just wanted to post my solution to this issue in case anyone else comes looking. What worked for me was to add a blank require line of the source file I was testing. Tested with jest --coverage (^24.8.0) and rewire module (^4.0.1).

Example:

    const rewire = require('rewire');
    const source = rewire('/js/source.js');
    require('/js/source.js'); <--------------------------------THIS LINE

    describe('Test hello function - hello()', function () {
        const hello = source.__get__('hello');

        it('should print out the word hello', function () {
            expect(hello()).toBe('hello');
        });
    });
