### ISSUE TITLE
rewire for an anonymous closure

### ISSUE THREAD

**Issue by huttli** [jhnns/rewire#42]
I thought my problem should have been resolved by reading issue 22 (https://github.com/jhnns/rewire/issues/22). But it didn't.

Here is the deal:

Instead of just a plain module, what if I put the module inside an anonymous closure. So something like this:
```javascript
(function() {
    var http = require("http"),
    fs = require("fs");
    function helper(app) {
        return {
            get_watch_list: function () { console.log('1');},
            update_watch_list: function (r_ip) {console.log('2'); }
        };
    }
    module.exports = helper;
}());
```
rewire this module, and try out the __get__ method gave me ReferenceError: *** is not defined.
```javascript
var rewire = require('rewire');
var helper = rewire('./helper');
helper.__get__('http');
helper.__get__('fs');
```
Can I rewire the result returned by the anonymous function?

**Comment by jhnns** [comment]
No, that is impossible. There is no way in JavaScript to access a function scope.
