### ISSUE TITLE
Rewire fails when using fs.readFileSync

### ISSUE THREAD

**Issue by kwakayama** [jhnns/rewire#43]
When I use sinon in combination with rewire and try to stub `fs.readFileSync`.
I get following error:
```
❯ npm test

rewireTest@1.0.0 test /Users/kwakayama/CODE/rewireTest mocha
readFile 1) "before each" hook

0 passing (9ms) 1 failing

1) readFile "before each" hook: TypeError: Cannot call method 'charCodeAt' of undefined at stripBOM (module.js:464:15) at Object.Module._extensions..js (module.js:474:19) at Module.load (module.js:356:32) at Object.load (/Users/kwakayama/CODE/rewireTest/node_modules/rewire/lib/moduleEnv.js:19:18) at internalRewire (/Users/kwakayama/CODE/rewireTest/node_modules/rewire/lib/rewire.js:50:15) at rewire (/Users/kwakayama/CODE/rewireTest/node_modules/rewire/lib/index.js:11:12) at Context. (/Users/kwakayama/CODE/rewireTest/test.js:15:20) at callFn (/Users/kwakayama/CODE/rewireTest/node_modules/mocha/lib/runnable.js:251:21) at Hook.Runnable.run (/Users/kwakayama/CODE/rewireTest/node_modules/mocha/lib/runnable.js:244:7) at next (/Users/kwakayama/CODE/rewireTest/node_modules/mocha/lib/runner.js:259:10) at Object._onImmediate (/Users/kwakayama/CODE/rewireTest/node_modules/mocha/lib/runner.js:276:5) at processImmediate as _immediateCallback

npm ERR! Test failed. See above for more details. npm ERR! not ok code 0
```
I created a sample repo to recreate the issue:
https://github.com/kwakayama/rewireTest
Can someone give me a hint how to fix this issue?

best,
kentaro

**Comment by jhnns** [comment]
Rewire uses node's `require()` and node's `require()` uses the `fs` module to actually load the module. Just do you rewiring *before* stubbing the `fs` module and everything should be fine.

**Comment by jhnns** [comment]
Close?

**Comment by kwakayama** [comment]
Hey @jhnns.

Thanks for your answer.
My problem is that I want to stub/modify the `fs.existsSync` before the `index.js` file is parsed.
I tried to stub before rewiring the `index.js` file, however then it throws the error (see above).
Do you have a solution for this scenario?

best,
kentaro

**Comment by jhnns** [comment]
Oh ... I think that is impossible, also without rewire. You need to wait for node loading the `index.js` (using the original `fs` module), but then you'd need to prevent node from actually executing the module. There is no hook or something to do that.

But you can use rewire to check if `privateFileContent` is correct. Then you could modify `privateFileContent` and test if `readFile` returns your modified `privateFileContent`. But imho that test would be too implementation specific...
