### ISSUE TITLE
Rewiring 'require'

### ISSUE THREAD

**Issue by LeonLiber** [jhnns/rewire#44]
Hi,

I came across a situation where I need to to test the parameters of a require().
In my case I dynamically generate the path of a module to require (because I support versioning) and want to make sure it does it as expected.

Does rewiring require makes sense in such situation? Is there a way to accomplish that?

Thanks!

**Comment by jhnns** [comment]
When the dynamic require() statement is immediately executed, rewire can't help here. You could create two dummy modules (text fixtures) and check afterwards the `require.cache`.

**Comment by bendrucker** [comment]
You can use https://github.com/thlorenz/proxyquire for this
