### ISSUE TITLE
Cannot convert null to object

### ISSUE THREAD

**Issue by mattdell** [jhnns/rewire#45]
I've decided to give rewire a try, but I'm getting an error.

I've simplified my code to just this
```
var React = require("react/addons");
var rewire = require("rewire");
```

But I keep getting an error saying "Cannot convert null to object at /Users/mdell/Work/site/node_modules/rewire/lib/index.js:16:22"

Any ideas?

**Comment by jhnns** [comment]
Do you use rewire in the browser context? The error is thrown when [deleting the `require.cache`](https://github.com/jhnns/rewire/blob/a3c91fd7bbdcdf5b2edce66bb1431b50b77b963f/lib/index.js#L16) so I assume it's not node.js?

**Comment by jackofseattle** [comment]
I can't repro this in a normal scenario - I do get it when I try to run the files in Jest. My guess is that Jest is using it's own module system which doesn't have a cache object.

I have a fix that seems to work for that environment - it's a simple check to see if require.cache exists before trying to delete from it.

**Comment by mattdell** [comment]
Yeah, this is when I'm trying to use it within Jest.

@jackofseattle, can you give me a code example of your fix?

**Comment by jhnns** [comment]
I don't know much about Jest, but afaik it brings its own mocking system. So I'd assume that rewire and Jest are not compatible.
