### ISSUE TITLE
Injecting another rewired module as a dependency

### ISSUE THREAD

**Issue by melbourne2991** [jhnns/rewire#46]
So let's say I am testing A, and A has B as a dependency. There is a dependency that B has that I want to modify (say it's fs because I dont want file writes when im testing), can I rewire B and then rewire A so it uses the rewired version of B instead of the actual dependency? So far i'm struggling with this eg:

//StubbedScraper.js
var	Scraper = rewire(__dirname + '/../../../lib/Scraper'),
	winstonStub = require(__dirname + '/../stubs/winston.stub'),
	listingStub = require(__dirname + '/../stubs/Listing.stub'),
	fsStub = require(__dirname + '/../stubs/fs.stub');

Scraper.__set__('Listing', listingStub);
Scraper.__set__('winston', winstonStub);
Scraper.__set__('fs', fsStub);

module.exports = Scraper;

------------

var specialScraper = rewire('../specialScraper')    <<< this has Scraper from above as a dependency
      stubbedScraper = require('../stubbedScraper)

specialScraper.__set('Scraper', stubbedScraper);

---------
So far it looks like even though it should be using the stubbed instance it's reverting to the original version of fs instead of my fs stub...is this behaviour expected, any solutions to this except writing a completely fresh Scraper stub.

**Comment by jhnns** [comment]
Yes, it should be possible to inject `b (rewired)` into `a (rewired)`.

In your test, just do

```javascript
var b = rewire("b");
var a = rewire("a");

a.__set__("b", b);
```
