### ISSUE TITLE
Strange module path string behaviour (with webpack) 

### ISSUE THREAD

**Issue by emmenko** [jhnns/rewire#47]
Hi,

not sure if this is related to `rewire` or `rewire-webpack`, so I will post it here anyway.

I'm having a strange behaviour when passing a path to the module that needs to be "rewired". Here the example:

```javascript
// this works
let foo = rewire('../foo')

// this doesn't work
let name = 'foo'
let foo = rewire('../' + name)
// TypeError: Cannot read property 'call' of undefined
//   at rewire (webpack:///~/rewire-webpack/lib/rewire.web.js:13:0)
// https://github.com/jhnns/rewire-webpack/blob/master/lib/rewire.web.js#L10
```

If I log the [argument](https://github.com/jhnns/rewire-webpack/blob/master/lib/rewire.web.js#L3) passed to `rewire` I get this

```bash
# when it works
233

# when it doesn't
../foo 
```
Basically when it works I get some sort of index which is the key of the `__webpack_modules__` object. When it fails, a string is passed hence the `TypeError` since it's not a valid key.

Any idea what's going on here? Any help is much appreciated, thanks :)

**Comment by jhnns** [comment]
You're using dynamic dependencies which are always problematic when a static module analyzer like webpack or browserify is used. In general, my advice is to avoid dynamic dependencies at all. Most of the time they can be replaced anyway. It's strange that your code doesn't know on which modules it depends on.

However, there are *a few* use-cases where dynamic dependencies are useful... I just wanted to say that you should probably re-think your architecture.

See further discussion at webpack/webpack#794

**Comment by emmenko** [comment]
@jhnns thx for the answer. I usually use static dependencies, just for this case I need it for some test utils where I can have the same setup for many modules (so I wanted to extrapolate the logic into a test util, hence the need for dynamic paths).

I found a workaround anyway, just wanted to clarify that behavior first :)

**Comment by jhnns** [comment]
Ok. It's just that I can't do much about it :wink:

**Comment by emmenko** [comment]
Yeah, sorry I forgot to close the issue :)
