### ISSUE TITLE
Rewiring within an anonymous function

### ISSUE THREAD

**Issue by lebolo** [jhnns/rewire#49]
I have a module that looks like

```javascript
"use strict";

var inherits = require('util').inherits;
var Task = require("task");
var db = require('db');

// Constructor
function FooTask() {
    Task.apply(this);
}
inherits(FooTask, Task);

// Prototype method
FooTask.prototype._run = function() {
    var self = this;

    // doSomething.call(self, null); // Method is mocked here!

    db.getStuff()
    .then( function(result) {
        doSomething.call(self, result); // Method is not mocked here!
        // Do other stuff
    })
    .fail( function(err) {
        console.error('Rut roh');
    });
};

// Private method
var doSomething = function(result) {
    // Does a bunch of stuff
};

// Return the module exports
module.exports = FooTask;
```

My spec file looks like

```javascript
var rewire = require('rewire');

var BaseTask = rewire("task");
var Task = rewire("fooTask");

// Some other tests

it("should test something", function(done) {
    Task.__with__({
        doSomething: function() {
            console.log('doSomething');
        },
        db: {
            getStuff: function() {
                // Return resolved promise
            }
        }
    })(function() {
        var testTask = new Task();
        var returnVal = testTask._run();
        expect(returnVal).toBe(0);
    });
});
```

When I run the test, the `doSomething` method is *not* mocked. Instead, the `_run` method calls the proper `doSomething`. If I were to run `doSomething` above the `db.getStuff` call, then the mocked version is called.

Is this expected? Is there anyway to mock `doSomething` within that callback?

**Comment by jhnns** [comment]
It seems like your examples lack some information. Where does the `TaskImporter` come from?

But reading from your examples I guess you've misunderstood the rewire API. rewire is no mocking lib that stubs methods on objects ([sinon](http://sinonjs.org/docs/) is an excellent mocking lib). rewire can be used to change internal variables of a module.

In your example, rewire would be useful to mock the `db` object without interfering with other modules:

```javascript
var sinon = require("sinon");
var FooTask = rewire("./FooTask.js");

FooTask.__with__({
    db: {
        getStuff: sinon.spy()
    }
})(function () {
        var testTask = new FooTask();
        var returnVal = testTask._run();
        expect(returnVal).toBe(0);
});
```

**Comment by lebolo** [comment]
Sorry,I fixed my example, _TaskImporter_ was the actual name of my method before I turned it into an example ;)

Isn't `doSomething` just an internal variable of the `FooTask` module? Why does `doSomething` change before `db.getStuff` but not within the callback of `db.getStuff`?

Either way, thank you for a great tool!

**Comment by lebolo** [comment]
I figured out the problem - and by dumbing down the example, I removed a very important aspect. My `_run` method returns a promise. And the actual `expect` (not the one above) is testing that the promise is rejected in a certain way. So I forgot to add `return returnVal` which is a promise after the `expect`.

Sorry, my fault! In short: if you're testing an async method, you have to return that promise for rewire's undo to take effect at the right time.

**Comment by jhnns** [comment]
Yep, that behavior is mentioned in the README :wink:
