### ISSUE TITLE
Skip Some Modules

### ISSUE THREAD

**Issue by jacobp100** [jhnns/rewire#50]
If you don't mutate some modules, would it be possible for them to keep the same instance?

**Comment by jhnns** [comment]
Please post an example of what you're trying to achieve.

**Comment by jacobp100** [comment]
```js
<module.js>
return {
    a: require('a'),
    b: require('b')
}
```
```js
<index.js>
var f = rewire('./module', { skipModules: ['./a'] });
var g = rewire('./module', { skipModules: ['./a'] });
f !== g
f.a === g.a
f.b !== g.b
```

**Comment by jhnns** [comment]
Sorry, but that's not how rewire works. It does not replace automatically your dependencies when the module is required, but it provides you with a way to change the internal variables (and thus overriding dependencies).

```javascript
// module.js
var a = require("a");
var b = require("b");
```

```javascript
var f = rewire("./module");
var g = rewire("./module");

f !== g

// Until now f and g both have the same instance of a and b
// Now you can change these internal variables

f.__set__("a", aMock);

// Now f and g won't share the same instance of a.
```

Please be aware, that if you export the dependencies as stated in your example, you are copying the reference of `a` on your `module.exports` object. Thus running `f.__set__("a", aMock);` won't change the reference attached to `module.exports`.

Just think of rewire just adding these two methods to your module:

```javascript
// module.js
var a = require("a");
var b = require("b");

exports.__set__ = function (key, value) {
    eval(key + " = " + value);
};
exports.__get__ = function (key) {
    return eval(key);
};
```
