### ISSUE TITLE
Incorrect functions called when functions have same names across different files.

### ISSUE THREAD

**Issue by ssshah5** [jhnns/rewire#52]
Hello,
First of all, thank you very much for writing and supporting rewire.

We are using rewire along with grunt, mocha and chai for unit-testing. Currently, we are triggering the tests of 3 of our main files through a single grunt command. These 3 index.js files (located in different  folders) have few functions with the same name for example a function getDocument is present in /folder1/index.js as well as /folder2/index.js. For each of the index.js files, we have a corresponding test-index.js file and a variable "Router" that is rewired to the particular location of index.js file as follows:

Router = rewire('/routes/folder1/index.js');
Router = rewire('/routes/folder2/index.js');
Router = rewire('/routes/folder3/index.js');

In each of the test files, we access a particular function by following commands:
![snippet](https://cloud.githubusercontent.com/assets/1467450/7033952/ffebe6d2-dd4b-11e4-975b-4cfb3c7d4d8c.png)

The problem occurs when a function like (getDocument) appears in more than one index.js files. In that situation, a testcase corresponding to /folder2/index.js that has its Router pointing to /folder2/index.js still calls the getDocument of /folder1/index.js. One of the workarounds was to change the name of the function so that no two functions between any of the index.js files have same names. However, this is not desirable.
I looked into other defects (open and closed ones) and seems like this problem is the one similar to caching where the file that has been rewired earlier (/folder1/index.js) has its functions in the cache and /folder2/index.js in unable to over-ride the function with same name. I also tried the following solution as was mentioned in one of the issues but it did not work for me:

var myModel = rewire('./lib/myModel');
require.cache[require.resolve('./lib/myModel')] = {
    exports: myModel
};

Any help/pointers on this issue would be much appreciated.
Thanks in advance!

**Comment by jhnns** [comment]
Could you set up a simple example repository (or a gist) that demonstrates the problem? It's hard to get a grasp of what is actually going on with such a description (though it is very extensive :grin:)

> where the file that has been rewired earlier (/folder1/index.js) has its functions in the cache and /folder2/index.js in unable to over-ride the function with same name

There is no such a "function cache"

**Comment by ssshah5** [comment]
Hey Johannes,
Thanks for the quick response and sorry for confusing you with extensive yet insufficient information. I will try my best to illustrate the problem here with some snippets from different files. 
I am trying to test 2 different functions, with the same name, which are located in 2 different files. The functions in both the files are as below:

File 1: home/routes/folder1/index.js
```
function getDocument(var1, var2, next) {
    var dbName = conf.get("name");
    var db = con.getCon(dbName);
    db.get(req.params.id, function (err, doc) {
       doSomething;
    });
} 
```
File 2: home/routes/folder2/index.js
```
getDocument = function(var1, var2, next) {
    var callback = function(err,var2) {
            doSomething;
     }
    db.get(var, callback);
};
```
Following is the configuration in my  /home/tests/test1.js to test the function in home/routes/folder1/index.js
```
var rewire = require("rewire"),
router = rewire('home/routes/folder1/index.js'),
access= {};
access.getDocument = router.__get__("getDocument");

//testcase

it('testing1', function (done) {
         var mock_db = {
               "get": function(var1,callback){
                }
          };
        var mock_db = {.........};
        var mock_con = {........};
       revert = router.__set__({db:mock_db, conf:mock_conf, con:mock_con}) ;
       access.getDocument(var1,var2,next) ;
});
```
Similarly, is the configuration in my /home/tests/test2.js to test the function in home/routes/folder2/index.js
```
var rewire = require("rewire"),
router = rewire('home/routes/folder2/index.js'),
access= {};
access.getDocument = router.__get__("getDocument");

//testcase

it('testing2', function (done) {
         var mock_db = {
               "get": function(var1,callback){
                        callback(false,var);
                }
          };
       revert = router.__set__({db:mock_db}) ;
       access.getDocument(var1,var2,next) ;
});
```
Problem:
When I launch the tests using "grunt test", the testcases in test2.js seems to run first and corresponding testcase for getDocument passes successfully.
However, when it reaches testcases in test1.js, the corresponding getDocument fails since its still pointing to getDocument defined in /folder1/index.js ((I can tell this from the error stack) rather than pointing to /folder2/index.js even though the var router in test2.js is rewired to /folder2/index.js.
All works fine if I name the functions differently but its desirable to keep the names same. I hope this clarifies the problem a bit better. 

I would appreciate any input/suggestions. I am still new to this so apologize if I missed any other essential detail.

**Comment by ssshah5** [comment]
Finally got the source of problem. 
In the folder1/index.js, I changed the getDocument to a function expression and voila!
```
function getDocument(var1, var2, next)
```
changed to 
```
var getDocument = function (var1, var2, next)
``` 
Not exactly sure why function expression worked as opposed to function declaration.

**Comment by jhnns** [comment]
Nice :+1:
