### ISSUE TITLE
rewire doesn't work with babel

### ISSUE THREAD

**Issue by damassi** [jhnns/rewire#55]
I've just finished porting all of my React.js code to ES6 and found that my tests have broken due to Rewire (seemingly) not supporting the new syntax.  

```
// DummyClass.js
import states from 'utils/states';

export default class DummyClass {
  constructor() {}
}

// DummyClass-spec.js
describe('Test', function() {
    it('should work', function() {
       var rewire = require('rewire');
       var DummyClass = rewire('./DummyClass');
       DummyClass.__set__('states', 'foo'); // throws ReferenceError: states is not defined
    })
});
```
However, when importing using `var states = require('utils/states')` everything is just fine.

Any assistance would be appreciated!

**Comment by srph** [comment]
Having the same issue as well.

**Comment by jhnns** [comment]
Yes, probably the same error as in jhnns/rewire-webpack#12

**Comment by jhnns** [comment]
Is React using Babel for transpiling?

**Comment by mikeyamadeo** [comment]
+1

Using Babel for transpiling.

**Comment by jhnns** [comment]
I can't see how this could be fixed by my side. As @sairion pointed out, babel is changing variable names. Thus all uses of `eval()` will not work as expected.

I hope babel will do something about it. Although `eval()` should not be used in day-to-day code, it is still part of the language and will not be deprecated.

**Comment by damassi** [comment]
This is super disappointing as Rewire is the most useful library ever!  It might be worthwhile to start a discussion with the Babel folks.  

I'll go ahead an close.

**Comment by doctyper** [comment]
Hm, then we may have a problem. Babel says it's not their issue: babel/babel#1337

**Comment by JustinTulloss** [comment]
For what it's worth, @speedskater has written an alternative that works with Babel's ES6 module compilation. https://github.com/speedskater/babel-plugin-rewire

**Comment by d4nyll** [comment]
Note that [`babel-plugin-rewire`](https://github.com/speedskater/babel-plugin-rewire) does not currently work with Babel 7. See [**Babel 7 Support? #209**](https://github.com/speedskater/babel-plugin-rewire/issues/209) for more details.
