### ISSUE TITLE
Can't rewire strict file

### ISSUE THREAD

**Issue by AgentME** [jhnns/rewire#58]
foo.js
```javascript
'use strict';

function foo() {
  console.log(document);
}

module.exports = foo;
```

```
> var rewire=require('rewire');
undefined
> var foo = rewire('./foo');
undefined
> foo.__set__('document', 5);
ReferenceError: document is not defined
    at Function.eval (eval at __set__ (/Users/chris/Coding/foo.js:71:19), <anonymous>:1:10)
    at Function.__set__ (/Users/chris/Coding/foo.js:71:5)
    at repl:1:5
    at REPLServer.self.eval (repl.js:110:21)
    at repl.js:249:20
    at REPLServer.self.eval (repl.js:122:7)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.emit (events.js:95:17)
    at Interface._onLine (readline.js:203:10)
    at Interface._line (readline.js:532:8)
> 
```

Works if "use strict" is removed. Babel automatically adds "use strict" to the tops of files when they're loaded, so rewire doesn't work with ES6/Babel modules.

**Comment by AgentME** [comment]
Oh this normally doesn't work. If you try to override a global (rather than a top-level variable) in a module, then a global is created that's visible outside of the rewired module. I don't think that seems useful in general. Maybe rewire should use strict mode inside its own function so that this always fails?

**Comment by jhnns** [comment]
Are you using rewire on the client-side?

**Comment by AgentME** [comment]
I was going to use it in Node to help test files that are intended to be used in browsers. I have a lot of tests right now where I set globals (like `global.document` to a jsdom object) before loading the files, but I run into issues occasionally when I want to set different globals to different modules I'm testing.

**Comment by jhnns** [comment]
You're right, the variable `document` can not created implicitly in strict mode. You just have to add it to the `global` object first. Then you should be able to `__set__` document just within a specific module.
