### ISSUE TITLE
[help needed] [discussion] Stubbing private var as constuctor 

### ISSUE THREAD

**Issue by hellboy81** [jhnns/rewire#67]
I have a problem with stubbing [`#validator.validate`](http://git.io/vtjwk) from [jsonschema](https://github.com/tdegrunt/jsonschema)

How can I inject stub into `require part`  or `proxyquire`?

In module:
```js
// require part
var validator = require('jsonschema').Validator
  
// SUT function
var v = new validator()
    
v.validate(..)
```

I am trying to do it with `rewire` in my tests:
    
```js
// require part
var rewire        = require('rewire');
    
// it part
// How can I create stub that acts as constructor
// Actually I need only v.validate to be stubbed
var validator = sandbox.stub()
    
// myMod is rewired module
myMod.__set__('validator', validator)
```

**Comment by jhnns** [comment]
Sorry, I won't explain how you write a constructor function in JavaScript. There are plenty of good tutorials on the internet...
