### ISSUE TITLE
Error message when calling __set__

### ISSUE THREAD

**Issue by jhorneman** [jhnns/rewire#70]
(I hope this is the right repo - it could be a rewireify issue.)

When I call `__set__` on a module, to mock a function it requires from another module, I get the following error message:

    PhantomJS 1.9.8 (Windows 7 0.0.0) ERROR
      TypeError: 'undefined' is not a function (evaluating 'function (revertArgs) {
              __set__.apply(null, revertArgs);
          }.bind(null, arguments.revertArgs)')

I've tried a lot of different things but I can't figure out where the problem is.

I've made a minimal reproduction repo here: [https://github.com/jhorneman/karma-browserify-repro](). (Just run npm install, then npm run test.)

I'm using Karma, Jasmine, Browserify, and Rewireify, under Windows 7.

**Comment by jhorneman** [comment]
(FWIW I've opened the same issue here: https://github.com/i-like-robots/rewireify/issues/11, and a workaround was found. There's likely still a real bug somewhere though.)

**Comment by jhnns** [comment]
Thx for providing a test repo. It looks like the error is only present in PhantomJS. Chrome and FF do not report errors.

After adding `console.log()` I found out that `typeof Function.prototype.bind` is undefined. Then I saw that [this is a known bug of PhantomJS 1.x](https://github.com/ariya/phantomjs/issues/13107). After adding a [polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind) in your test, the test did work.

**Comment by jhorneman** [comment]
Thank you!
