### ISSUE TITLE
Add ability to get all vars

### ISSUE THREAD

**Issue by markelog** [jhnns/rewire#72]
It would be cool to do this - 

```js
var vars = rewire('module').__get__('*');

/*
vars = {
   key1: value1,
   key2: value2
}
*/
```

**Comment by jhnns** [comment]
Thx for your suggestion.

Since there are more important issues to solve (like babel compatibility), I don't think that this will be implemented soon. Especially because I don't want people to misuse `__get__` to evaluate all kind of expressions.

**Comment by markelog** [comment]
Alrighty

**Comment by abou7mied** [comment]
Is there any updates regarding that issue?

I need to __get__ a variable but I don't know it's accurate name, so It would be good if there is an ability to get all variables then I could use regex to find it from the returned list.
