### ISSUE TITLE
In Jenkins, rewire throws Error: Cannot find module '../model'

### ISSUE THREAD

**Issue by timph** [jhnns/rewire#74]
Even though, I got successful tests running locally. In Jenkins environment, rewire just throws error on our module loading for unit test.

```LimitModel = rewire('../models/LimitModel');```

where the limitModelTest.js is in web-notifications/test and limitModel is in web-notfiications/model

> [0m  1) Limits Model tests "before all" hook:
> [0m[31m     Error: Cannot find module '../models/LimitModel'[0m[90m
>       at Function.Module._resolveFilename (module.js:338:15)
>       at internalRewire (/jobvolume/web-modules/workspace/web-notifications/node_modules/rewire/lib/rewire.js:23:25)
>       at rewire (/jobvolume/web-modules/workspace/web-notifications/node_modules/rewire/lib/index.js:11:12)
>       at Context.<anonymous> (/jobvolume/web-modules/workspace/web-notifications/tests/limitsModelTests.js:25:22)
>       at Hook.Runnable.run (/jobvolume/web-modules/workspace/web-notifications/node_modules/mocha/lib/runnable.js:217:15)
>       at next (/jobvolume/web-modules/workspace/web-notifications/node_modules/mocha/lib/runner.js:258:10)
>       at Object.<anonymous> (/jobvolume/web-modules/workspace/web-notifications/node_modules/mocha/lib/runner.js:275:5)
>       at Object._onImmediate (/jobvolume/web-modules/workspace/web-notifications/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31)
  >     at processImmediate [as _immediateCallback] (timers.js:363:15)

Any idea what's going wrong here?

**Comment by jhnns** [comment]
Is this still an issue?

Could you add a `console.log(module.parent)` [here](https://github.com/jhnns/rewire/blob/851c1032dcf4b15a251eef06e9f10b57a57bc31c/lib/index.js#L11) and compare the result in both envs?

**Comment by timph** [comment]
Hi Johannes,
I forgot to follow up. No, it's not an issue. It's a Capitalized LimitModel.js (wrong) vs limitModel.js (right). It's working fine with capitalized filename in Mac, but won't work for Jenkins env - linux. That is all. Sorry for the trouble :)

**Comment by jhnns** [comment]
No problem :grin:
