### ISSUE TITLE
mocking part of an object seems to delete functions that aren't mocked

### ISSUE THREAD

**Issue by Coaxial** [jhnns/rewire#75]
Consider the following:

```javascript
// app.js
module.exports = App;

function App() {
  return this;
};

App.prototype.say = function(str) {
  console.log('console.log says "' + str + '"');
  console.dir('console.dir says "' + str + '"');  
};
```

```javascript
// test.js
var expect = require('chai').expect;
var rewire = require('rewire');
var App = rewire('./app');

describe('App', function() {
  it('will not fail', function() {
    var test_app = new App();
    expect(test_app.say('foobar')).to.not.throw;
  });

  it('will not fail either', function() {
    var mockConsole = {
      log: function() {},
      dir: function() {}
    };
    var revert = App.__set__('console', mockConsole);
    var test_app = new App();
    expect(test_app.say('foobar')).to.not.throw;
    revert();
  });

  it('should not fail', function() {
    var mockConsole = {
      log: function() {},
    };
    var revert = App.__set__('console', mockConsole);
    var test_app = new App();
    expect(test_app.say('foobar')).to.not.throw;
    revert();
  });
});
```

Output:
```
  App
console.log says "foobar"
'console.dir says "foobar"'
    ✓ will not fail
    ✓ will not fail either
    1) should not fail


  2 passing (18ms)
  1 failing

  1) App should not fail:
     TypeError: undefined is not a function
      at App.say (app.js:9:11)
      at Context.<anonymous> (test.js:28:21)
```

The last test doesn't pass because it seems that rewire overwrites console with mockConsole, erasing the functions that aren't mocked in the process. The failure points at `app.js:9` with the message "undefined is not a function" which is where `console.dir` is called.

Is this intended behavior? If so, how to mock only `console.log` in `App` and leave the other `console` functions intact?

**Comment by Coaxial** [comment]
On the other hand, the following doesn't seem to be as bad as the README depcits it:

```javascript
var consoleMock = {
  log: function() { }
};

App.__set__('console.log', consoleMock.log);

console.log('not overriden');
```

The `console.log` in App will be using the mocked version while `console.dir` will still behave normally. Within the test, `console.log` isn't mocked and still behaves as normal.

I'm not sure if I'm missing the point or if doing it this way used to override `console.log` outside of `App` but it's the only way I can get rewire to not break anything that isn't mocked on an object.

**Comment by brennon** [comment]
It *does* work if you use dot notation, though.

Based on the inordinate amount of time I spent trying to write a pull request to fix this, I'm convinced this is the intended behavior. It is, however, completely counterintuitive, as long as this difference between passing an object and a string in dot notation is not called out clearly in the docs.

**Comment by Coaxial** [comment]
Are you saying there is a difference between this:
```javascript
Module.__set__('console.log', function() { });
```

and that:
```javascript
var consoleMock = {
  log: function() { }
};
Module.__set__('console.log', consoleMock.log);
```

Maybe I'm tired but my understanding from the README is that setting `console.log` to whatever function will override the global `console` object and so your `console.log` will be changed not only within `Module` but also everywhere else `console.log` is used. But from the examples above, it doesn't seem to be the case. What gives?

**Comment by brennon** [comment]
No, my comment regards your first post (the one to which the title of the issue seems to refer).

**Comment by jhnns** [comment]
There is no "magic mocking" behavior behind rewire. Calling `__set__(variable, value)` will just evaluate `variable = value` inside the module's scope. If your mock does not provide all `console` methods `, there will probably be errors.

You could use prototype inheritance instead:

```javascript
var consoleMock = Object.create(console);
consoleMock.log = function () {};
App.__set__('console', consoleMock);
```

Writing `App.__set__('console.log', consoleMock.log);` will also work, but if you do so, you don't need rewire at all. It the same like writing `console.log = consoleMock.log`. Using dot notation was never intended and results in the opposite: You won't mock it, but change it globally.
