### ISSUE TITLE
Can't mock files from my filesystem

### ISSUE THREAD

**Issue by Raulucco** [jhnns/rewire#76]
If trying to mock a function exported from a file on my module the build expression is illegal as the variable name is not valid throws an error: unexpected token, see [question](http://stackoverflow.com/questions/32744314/nodejs-testing-with-rewire-and-mocha-syntaxerror-unexpected-token). 
I'm on a windows 7 x64
```
P:\>node -v
v4.1.0

P:\>npm -v
3.3.3
```

**Comment by jhnns** [comment]
You need to pass in variables names for `__set__`, not module paths.

**Comment by machineghost** [comment]
The README could be improved to clarify this (and prevent future issues like the four existing ones of this nature).

Right now you have one example `myModule.__set__("fs", fsMock);` ... where it looks like you're passing in a "path to a module" (ie. "fs").  Having a simple example of rewiring a local import (ie. something starting with `../` or `./`) would most likely alleviate this.

**Comment by jhnns** [comment]
Sounds good 👍 
Are you up for a PR?
