### ISSUE TITLE
Usage with ES6 static methods

### ISSUE THREAD

**Issue by brenolf** [jhnns/rewire#80]
I don't know why, but when using rewire with mocha, I'm not able to use `__set__` inside `before` blocks when the methods being tested are `static`. It doesn't rewire at all and I need to use it before the upmost `describe`.

For instance, this works:

```js
'use strict'

const EncryptionService = rewire('../app/Services/EncryptionService')

EncryptionService.__set__({
  bcrypt: {
    // ...
  }
})

describe('EncryptionService', () => {
// ...
})
```

Whereas the following uses default `bcrypt`:

```js
'use strict'

const EncryptionService = rewire('../app/Services/EncryptionService')

describe('EncryptionService', () => {
  before(() => {
    EncryptionService.__set__({
      bcrypt: {
        // ...
      }
    })
  })
// ...
})
```

**Comment by jhnns** [comment]
Could you setup a small example that demonstrates the problem?

**Comment by brenolf** [comment]
I'm closing this issue because it no longer affects me. If this shows up again I can open another one.
