### ISSUE TITLE
When using rewire and sinon fakeTimer, order matters?

### ISSUE THREAD

**Issue by jhohlfeld** [jhnns/rewire#87]
Hey everyone,

Did you happen to come to use sinon's fakeTimers along with rewire? I have an issue that i think is worth mentioning.

If i rewire a module on the global scope and set the fakeTimer up afterwards, it does not seem to reach the injected module. However, when rewiring the module on the local level (after the fakeTimer has been set up) it's perfectly fine.

I posted a question on SO: http://stackoverflow.com/questions/34885024/sinon-faketimers-do-not-affect-modules-beeing-required-with-rewire-js-sometimes

Hope you can clarify.
J

**Comment by jhnns** [comment]
Thank you for pointing that out. I've answered it on SO and added a note in the README.
