### ISSUE TITLE
Proxy hackery to make mocha chai sinon tests prettier

### ISSUE THREAD

**Issue by edsharp** [jhnns/rewire#91]
Hi

I've been playing with wrapping the result of rewire in a proxy:

```js
const some_module = rewire('./some_module.js');

__some_module = new Proxy(some_module, {
  getOwnPropertyDescriptor: function(target, prop) {
    // Not sure if this is the best way to fake a property description
    var t = {};
    t[prop] = some_module.__get__(prop);
    return Object.getOwnPropertyDescriptor(t, prop);
  },

  defineProperty: function(target, prop, methodDesc) {
    // sinon uses this to set the spy/stub or reset the original
    some_module.__set__(prop, methodDesc.value);

    return true;
  },

  get: function(target, prop) {
    return some_module.__get__(prop);
  },

  set: function() {
    throw new Error('You cannot directly set properties');
  }
});
```

In conjunction with a sinon sandbox, it allows for easy-to-write tests, in a style I find easier than the existing __with__ option. Like this:

```js
'use strict';

const chai         = require('chai'),
  sinon            = require('sinon'),
  sinonChai        = require('sinon-chai'),
  rewire           = require('rewire'),
  Proxy            = require('harmony-proxy');

const some_module  = rewire('./some_module.js'),
  SomeModule       = some_module.SomeModule;

chai.use(sinonChai);

const should = chai.should();

describe('module fake_http_client', function() {
  var sandbox;
  var some_module;

  before(function() {
    sandbox = sinon.sandbox.create();

    __some_module = new Proxy(some_module, {}); // INSERT CODE FROM ABOVE
  });

  afterEach(function() {
    sandbox.restore();
  });

  describe('SomeModule', function() {
    describe('instances', function() {
      var instance;

      beforeEach(function() {
        instance = new SomeModule();
      });

      it('call a private function from a public method that passes through args', function() {
        sandbox.stub(__some_module, 'privateMethod');
        instance.publicMethodThatCallsPrivateMethod('foo');
        __some_module.privateMethod.should.have.been.calledWith('foo');
      });
    });
  });
});
```

With this approach, when the sandbox is restored, so are any spied/stubbed private functions, meaning that without having to be careful, I can setup a stub or spy in the test or the beforeEach hook.

The Proxy is noddy and could certainly be improved for edge cases. I'd love to hear your thoughts on my approach, in particular if there are any big flaws! It seems to be working in a suite of tests I've got in a project. I'm considering packaging it into an npm package 'rewire-proxy' or somesuch. Although I imagine it would be even better if it were available within the rewire package.

Best wishes

Edward

Edited to use __some_module as proxy for private access. Seems to give better indication that you're working with internals.

**Comment by jhnns** [comment]
Thx for sharing this. Proxies will definitely play a big role in the future of mocking, especially because ES2015 modules leave us with many puzzles to solve.

Since you were asking for feedback: To be honest, I think your example is too complex for the thing you're trying to achieve. I would be careful to check private function calls because they are too implementation dependent. Soon you'll find yourself in a situation where you're constantly adjusting your tests because they rely too much on internals instead of the public API.

I clearly undestand the motivation behind this: sinon's `sandbox` is a nice thing, but it can't be used with `__set__`. But have you tried using rewire's `__with__` method? It's also a "sandbox" which reverts its modifications afterwards. So, in your example, you'd write:

```javascript
describe('module fake_http_client', function() {
  describe('SomeModule', function() {
    describe('instances', function() {
      const instance;

      beforeEach(function() {
        instance = new SomeModule();
      });

      it('call a private function from a public method that passes through args', function() {
        const privateMethod = sinon.spy();
      
        some_module.__with__({
          privateMethod
        })(function () {
          instance.publicMethodThatCallsPrivateMethod('foo');
          privateMethod.should.have.been.calledWith('foo');
        });
      });
    });
  });
});
```

It does the same thing afaict and requires less "hackery".

**Comment by edsharp** [comment]
Thanks for your feedback. I'll take some time to think about what you've said. 

I certainly like that idea that well tested public methods should negate the need for private method testing. 

What I'm wrangling with is where I've got maybe three public methods that shared a lot of overlapping logic. In those cases, I abstracted the shared logic into a private method, but I wanted it truly private, so it's just a function rather than an instance method. 

Having done that, I thought the most succinct way to test it was to test that the private function behaves as expected; and then test that the public methods call the private function in the way I'd expect them to.

With that being the case, I then found it useful to stub/spy the private functions. I do wonder if there's a better pattern altogether.

FWIW since writing the original post, I've got quite a bit of mileage out of this approach. I've extracted the proxy wrapping of rewire into a module of its own. By using the proxy, sinon's sandboxing works because sinon uses `defineProperty` and the proxy then translates that into to appropriate `__set__` calls.

The `__with__` approach you outlined does indeed work, although I really like that with the proxy I can then use the same syntax regardless of whether I'm stubbing private functions or public instance methods: I just use `sandbox.stub(__some_module, 'privateMethod')`. Also, in my simple example I only stubbed a method in a single test. In my actual usage, I sometimes stub a privateMethod in the `before` or `beforeEach` calls which works with the proxy approach. I think it would take a few more lines of code to replicate using just `__get__` and `__set__` or `__with__` and possibly require some balancing calls in `after` or `afterEach`. The sinon sandbox reliably restores everything with each top-level `afterEach`.

Finally, I like the syntactic sugar of calling `__some_module.privateConst` vs `some_module.__get__('privateConst')`. I reckon the double underscore prefix is enough to indicate that I'm operating on the rewired version of the module, but the syntax is as if I'd exported privateConst by name on the `module.exports`. I happen to use symbols to keep my private instances properties semi-private (at least private enough that they don't pollute the public instance properties).

In the module, I define the symbols which means in the tests I end up doing `myInstance[__some_module.privatePropertyXSymbol]` to access those symbol properties. I reckon that's a best-of-both worlds approach: I get the semi-private neatness of using symbol properties; I can still access the symbol properties in tests; and with the syntactic sugar of the proxy approach, getting at the symbols isn't arduous :)

Anyway, thanks for contributing rewire to the community. For fun, I think I'll publish the rewire proxy module I mentioned as well as some working examples. It is heavier in weight than just using `__with__` within a single test, but then it also has some other advantages.

**Comment by jhnns** [comment]
> Having done that, I thought the most succinct way to test it was to test that the private function behaves as expected; and then test that the public methods call the private function in the way I'd expect them to.

Yes, that's the only use-case I can think of where testing private methods is actually better than writing 3 times almost the same testing code just to test the public API.

And yes, writing ` __some_module.privateConst` is definitely nicer than `some_module.__get__('privateConst')`. Proxies will be awesome for this kind of hackery.

I also like your idea about using symbols. That approach doesn't even require rewire or some other library, it's just vanilla JS. The only thing that bothers me is that you have to modify your code just for your tests which is not a good thing imho.

Anyways, I think I'll take this as inspiration for the next major version of rewire :grin:
