### ISSUE TITLE
__set__ does not accept '../lib/something.js'

### ISSUE THREAD

**Issue by r4j4h** [jhnns/rewire#92]
If I use rewire to mock a script and try to pass it a block like 

```javascript
        var instrumentation = rewire('../../code-coverage/lib/instrumentation.js');

        console.log(instrumentation);

        instrumentation.__set__({
            console: consoleMock,
            'shelljs': shelljsMock,
            '../../lib/stripslashes.js': stripTrailingSlash,
            'minimist': minimistMock,
        });
```

I get `SyntaxError: Unexpected token .`:

```
  Message:
    SyntaxError: Unexpected token .
  Stack:
    SyntaxError: Unexpected token .
        at Object.__set__ (/project/code-coverage/lib/instrumentation.js:86:19)
        at Object.<anonymous> (/project/spec/lib/remove-instrument-for-coverageSpec.js:16:25)
```

If I remove `'../../lib/stripslashes.js': stripTrailingSlash` it gets past that and tries to run the code, so I believe the `../` is messing `__set__` up.

I also tried

```
        instrumentation.__set__('../../lib/stripslashes.js', stripTrailingSlash);
```

and got the same result.

**Comment by r4j4h** [comment]
Ah, I just realized my mistake. I should not be trying to "mock" the require call, but the global variable the result is stored in.

```js
var stripTrailingSlash = require('../../lib/stripslashes.js').stripTrailingSlash;
```

So in this case I should just pass `stripTrailingSlash`.

Thank you and I apologize for this mistake. I am going to leave it here in case it helps someone else, but please free to close it if you would like.

**Comment by jhnns** [comment]
Hehe, no problem, you're not the first one :wink:.
